import './globals.css';

import { Toaster } from './_components/ui/sonner';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='pt-br'>
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
