import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Sidebar from './_components/sidebar';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <body className={`${inter.className} antialiased`}>
        <div className='flex h-full gap-8'>
          <Sidebar />
          <main className='ml-[272px]'>{children}</main>
        </div>
      </body>
    </html>
  );
}
