import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { SetUserInfo } from './_components/common/set-user-info';
import Sidebar from './_components/sidebar';
import { Toaster } from './_components/ui/sonner';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <body className={`${inter.className} antialiased`}>
        <div className='flex h-full gap-8'>
          <Sidebar />
          <main className='ml-[272px] w-full'>{children}</main>
          <Toaster />
        </div>
        <SetUserInfo />
      </body>
    </html>
  );
}
